import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Hero from "@/components/layout/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MealMaster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Hero/>
        {children}
      </body>
    </html>
  );
}
